server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nizaamudien-abbas/{application}-config.git
#          uri: file://${HOME}/work/development/{application}-config
          repos:
            prod:
              pattern: '*/prod'
              uri: https://github.com/nizaamudien-abbas/{application}-config-prod.git
#              uri: file://${HOME}/work/development/{application}-prod-config
